# Generated by Django 6.1.1 on 2026-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
