# Generated by Django 6.1.1 on 2026-09-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitem_book_orderitem_unique_book_per_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_book_per_order',
        ),
    ]
