# Generated by Django 6.1.1 on 2026-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('order', '0007_remove_orderitem_unique_book_per_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'book'), name='unique_book_per_order'),
        ),
    ]
