# Generated by Django 6.1.1 on 2026-09-27 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('biography', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EDUCATION', 'Education'), ('TECHNOLOGY', 'Technology'), ('SELF_HELP', 'Self Help'), ('FICTIONAL', 'Fictional'), ('HORROR', 'Horror')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField()),
                ('cover_image', models.ImageField(blank=True, upload_to='book_cover_images')),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('publication_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)])),
                ('language', models.CharField(default='English', max_length=10)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(blank=True, related_name='books', to='catalog.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='catalog.genre')),
                ('publisher', models.ManyToManyField(blank=True, related_name='books', to='catalog.publisher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='catalog_boo_is_acti_77f529_idx'), models.Index(fields=['is_active', 'created_at'], name='catalog_boo_is_acti_d55bc9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='book_price_non_negative')],
            },
        ),
    ]
